# Generated by Django 3.1.2 on 2020-10-06 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(help_text='Fabricante', max_length=30)),
                ('model', models.CharField(help_text='Modelo', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='OwnerState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aircraft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aircrafts.aircraft')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LoadState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pax', models.IntegerField(help_text='N° de passageiros a bordo')),
                ('cargo', models.IntegerField(help_text='Kg de Cargo a bordo')),
                ('aircraft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aircrafts.aircraft')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Characteristic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('range', models.IntegerField(help_text='Alcance')),
                ('category', models.CharField(choices=[('C', 'Cargo'), ('P', 'Passengers')], max_length=1)),
                ('max_cargo', models.FloatField(help_text='Nº máx de Cargo em Kg')),
                ('max_passengers', models.IntegerField(help_text='Nº máx de Passageiros')),
                ('aircraft', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='aircrafts.aircraft')),
            ],
        ),
    ]
