# Generated by Django 3.1.2 on 2020-10-09 22:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icao24', models.CharField(help_text='Código obtido no Opensky Network', max_length=6)),
                ('manufacturer', models.CharField(help_text='Fabricante', max_length=30)),
                ('model', models.CharField(help_text='Modelo', max_length=15)),
                ('range', models.IntegerField(help_text='Alcance')),
                ('category', models.CharField(choices=[('C', 'Cargo'), ('P', 'Passengers')], max_length=1)),
                ('cargo_capacity', models.FloatField(help_text='Nº máx de Cargo em Kg')),
                ('passengers_capacity', models.IntegerField(help_text='Nº máx de Passageiros')),
                ('fuel_capacity', models.FloatField(help_text='Capacidade de combustível em Kg')),
                ('cruise_altitude', models.IntegerField(help_text='Altitude de cruseiro em Feets')),
                ('cruise_speed', models.IntegerField(help_text='Velocidade de cruseiro em Knots')),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pax', models.IntegerField(default=0, help_text='N° de passageiros a bordo')),
                ('cargo', models.IntegerField(default=0, help_text='Kg de Cargo a bordo')),
                ('fuel', models.FloatField(default=0, help_text='Kg de Combustível a bordo')),
                ('aircraft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aircrafts.aircraft')),
                ('owner', models.ForeignKey(help_text='Dono da aeronave', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
