# Generated by Django 3.1.2 on 2020-10-09 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('airports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.FloatField(help_text='Distância em Nm')),
                ('rate', models.FloatField(default=1.0)),
                ('arrival', models.ForeignKey(help_text='Chegada', on_delete=django.db.models.deletion.CASCADE, related_name='arrival', to='airports.airport')),
                ('departure', models.ForeignKey(help_text='Saída', on_delete=django.db.models.deletion.CASCADE, related_name='departure', to='airports.airport')),
            ],
        ),
    ]
