# Generated by Django 3.1.2 on 2020-10-06 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aircrafts', '0001_initial'),
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Airline',
        ),
    ]
