# Generated by Django 3.1.2 on 2020-10-06 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_auto_20201006_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='airline',
            name='name',
            field=models.CharField(default='name', max_length=30),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Finances',
        ),
    ]
