# Generated by Django 3.1.2 on 2020-10-06 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_auto_20201006_1149'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Airline',
        ),
    ]
