# Generated by Django 3.1.2 on 2020-10-06 14:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('icao', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('uf', models.CharField(max_length=2)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('length', models.FloatField()),
                ('width', models.FloatField()),
                ('operation_mode', models.CharField(choices=[('I', 'IFR'), ('V', 'VFR'), ('V/I', 'VFR/IFR')], help_text='Modo de operação', max_length=3)),
                ('rate', models.FloatField(default=1.0)),
            ],
        ),
        migrations.CreateModel(
            name='AirportLicense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airports.airport')),
                ('user', models.ForeignKey(help_text='Titular', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
